# Generated by Django 4.0.6 on 2022-07-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_page_follow_requests_page_followers_page_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pages', to='page.tag'),
        ),
    ]
