# Generated by Django 4.0.6 on 2022-07-07 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0003_alter_page_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=[], related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
