# Generated by Django 4.0.6 on 2022-07-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
