# Generated by Django 4.0.6 on 2022-07-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_s3_path',
        ),
        migrations.AddField(
            model_name='user',
            name='image_s3_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
